#!/bin/bash
#
# Copyright (C) 2015 Red Hat Inc.
# Author: Salim Badakhchani <sal@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Uncomment to debug script
#set -x

# Check user priviledges
if [ "$USER" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
exit
fi

echo -e "# Installing Base packages"
yum -y install java links mailx mlocate patch sos tree unzip wget

echo -e "# Installing Nexus"
wget http://www.sonatype.org/downloads/nexus-latest-bundle.tar.gz
mkdir /var/opt/sonatype 
tar zxfv nexus-latest-bundle.tar.gz -C /var/opt/sonatype
mv /var/opt/sonatype/nexus-*/ /var/opt/sonatype/nexus
cp ~/workspace/ose-devops-demo/nexus/nexus-client /var/opt/sonatype/nexus/bin/
useradd nexus -d /var/opt/sonatype/nexus/
chown -R nexus:nexus /var/opt/sonatype /var/run/nexus/
cp /var/opt/sonatype/nexus/bin/nexus /etc/init.d/
chkconfig nexus on

cp -p /etc/init.d/nexus /etc/init.d/nexus.orig
cat > /tmp/nexus.patch << 'EOF'
--- /etc/init.d/nexus   2015-05-19 23:17:30.000000000 +0200
+++ /etc/init.d/nexus   2015-06-15 16:16:18.867999970 +0200
@@ -11,7 +11,7 @@
 # These settings can be modified to fit the needs of your application
 
 # Set this to the root of the Nexus installation
-NEXUS_HOME=".."
+NEXUS_HOME="/var/opt/sonatype/nexus"
 
 # If specified, the Wrapper will be run as the specified user.
 
@@ -20,7 +20,7 @@
 # NOTE - This will set the user which is used to run the Wrapper as well as
 #  the JVM and is not useful in situations where a privileged resource or
 #  port needs to be allocated prior to the user being changed.
-#RUN_AS_USER=
+RUN_AS_USER=nexus
 
 # Application
 APP_NAME="nexus"
@@ -31,7 +31,7 @@
 PRIORITY=
 
 # Location of the pid file.
-#PIDDIR="."
+PIDDIR="/var/tmp"
 
 # If uncommented, causes the Wrapper to be shutdown using an anchor file.
 #  When launched with the 'start' command, it will also ignore all INT and
@@ -549,4 +549,4 @@
         ;;
 esac
 
-exit 0
\ No newline at end of file
+exit 0
EOF
(cd / && patch -p0) < /tmp/nexus.patch
rm -f /tmp/nexus.patch

cp -p /var/opt/sonatype/nexus/bin/jsw/conf/wrapper.conf /var/opt/sonatype/nexus/bin/jsw/conf/wrapper.conf.orig
cat > /tmp/wrapper.patch << 'EOF'
--- /var/opt/sonatype/nexus/bin/jsw/conf/wrapper.conf   2015-10-27 17:34:49.964000000 -0400
+++ /var/opt/sonatype/nexus/bin/jsw/conf/wrapper.conf   2015-10-27 16:46:15.286000000 -0400
@@ -51,7 +51,7 @@
 # How much to wait for application to start up (increase on slower machines if needed)
 wrapper.startup.timeout=0
 # How much to wait for application to shutdown
-wrapper.shutdown.timeout=300
+wrapper.shutdown.timeout=10
 
 # Make wrapper reload configuration between app restarts
 # and set exit code 12 as "RESTART" command
EOF
(cd / && patch -p0) < /tmp/wrapper.patch
rm -f /tmp/wrapper.patch

rm -f ~/workspace/ose-devops-demo/nexus-latest-bundle.tar.gz

echo -e "# Starting Nexus server"  
service nexus start

echo -e "# Stopping firewall"
service firewalld stop
chkconfig firewalld off
