#!/bin/bash
#
# Copyright (C) 2015 Red Hat Inc.
# Author: Salim Badakhchani <sal@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Uninstall
# service gogs stop && userdel -rf git && rm -rf /var/spool/mail/git && rm /etc/init.d/gogs && mysqladmin drop gogs

# Uncomment to debug script
#set -x

# Check user priviledges
if [ "$USER" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
exit
fi

echo -e "# Installing Git SCM"
mkdir -p /home/git/gogs
useradd -U -r -s /usr/bin/git-shell -d /home/git/ git
[ -f "/tmp/gogs_v0.6.15_linux_amd64.zip" ] || wget -O /tmp/gogs_v0.6.15_linux_amd64.zip http://7d9nal.com2.z0.glb.qiniucdn.com/gogs_v0.6.15_linux_amd64.zip
unzip /tmp/gogs_v0.6.15_linux_amd64.zip -d /home/git/
mkdir /home/git/gogs/log
touch /home/git/gogs/log/gogs.log
ln -s /home/git/gogs/scripts/init/centos/gogs /etc/init.d/gogs
chmod +x /home/git/gogs/scripts/init/centos/gogs
chown -R git:git /home/git
[ -f "/etc/shells.orig" ] || echo -e "/usr/bin/git-shell" >> /etc/shells

echo -e "# Starting mysql server"
service mysqld start
chkconfig mysqld on

echo -e "Creating database"
mysqladmin create gogs

echo -e "# Starting gogs server"
service gogs start
chkconfig gogs on
