#!/bin/sh
#
# Copyright (C) 2015 Red Hat Inc.
# Author: Salim Badakhchani <sal@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Uncomment to debug script
#set -x

# Check user priviledges
if [ "$USER" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
exit
fi

# Turn off Jenkins if its running
[[ "$(rpm -qa | grep jenkins)" ]] && service jenkins stop && yum -y remove jenkins && rm -rf /var/lib/jenkins

# Install packages
yum -y install java mail wget
wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
yum install -y jenkins

# Setup environment
JDK=$(rpm -qa | grep openjdk | sort -n | tail -1)
alternatives --install /usr/bin/java java /usr/lib/jvm/${JDK}/bin/java 0

# Backup Jenkins
cp -af /var/lib/jenkins /var/lib/jenkins.orig

# Start up Jenkins
service jenkins start
chkconfig jenkins on

if [ ! -f /usr/bin/mvn ]; then
    # Setup Maven
    wget http://apache.arvixe.com/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
    tar zxfv apache-maven-3.3.3-bin.tar.gz -C /usr/lib/
    alternatives --install /usr/bin/mvn mvn /usr/lib/apache-maven-3.3.3/bin/mvn 0
else
    echo -e "Maven already installed..."
fi

echo -e "# Initialising plugin list..."
while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8080"; do echo -e "# Retrying...please be patient" && sleep 12 ; done
curl http://localhost:8080
curl -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' | \
curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack

if [ ! -f jenkins-cli.jar ]; then
    echo -e "# Retrieve jenkins client"
    wget http://localhost:8080/jnlpJars/jenkins-cli.jar
else
    echo -e "# Jenkins client already installed"
fi

PLUGINS="git \
openshift-deployer \
delivery-pipeline-plugin \
promoted-builds \
authorize-project \
build-pipeline-plugin \
conditional-buildstep \
copyartifact \
github-api \
github \
ssh-agent \
matrix-project \
role-strategy"

java -jar jenkins-cli.jar -s http://localhost:8080 install-plugin ${PLUGINS}

# Configure Jenkins
alias cp='cp'
cp -af overlay/* /var/lib/jenkins
chown -R jenkins:jenkins /var/lib/jenkins

# Restart Jenkins server
service jenkins restart
