#!/bin/bash
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

# Uncomment to debug script
#set -x

# Check user priviledges
if [ "$USER" != "root" ]; then
    echo -e "\n# This script requires root priviledges to run"
exit
fi

echo -e "# Installing Openshift origin PAAS"
./openshift/openshift-origin

echo -e "# Installing Jenkis Continuous Integration"
./jenkins/jenkins

echo -e "# Installing Nexus Repository Manager"
./nexus/nexus

